#!/bin/bash -ex

###Config Vars
DB_NAME=ghost
DB_USER=ghost
DB_PASS=$(mcookie)

USER=node
INSTALL_DIR="/opt/ghost"

CHECK_USER="/usr/local/lib/node_modules/ghost-cli/lib/utils/check-root-user.js"

service mysql start

#Create mysql user and table
mysql --user=root --password=$MYSQL_PASS --batch --execute "CREATE DATABASE $DB_NAME; GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON $DB_NAME.* TO $DB_USER@localhost IDENTIFIED BY '$DB_PASS'; FLUSH PRIVILEGES;"

# Set node version to 8.x - recommended version by Ghost: https://docs.ghost.org/faq/node-versions/
n 8
n prune # remove default 10.x node version

mkdir $INSTALL_DIR

npm i -g ghost-cli

sed -i '/function checkRootUser/a return 0;' $CHECK_USER
sed -i '/const isRootInstall/a return 0;' $CHECK_USER

cd $INSTALL_DIR

#adding ghost user via install seems to cause issues
adduser ghost --gecos ",,," --disabled-password
echo "ghost:ghostpass" | chpasswd

#sudo complains about hostname not being tkldev, this is a temporary fix
sed -i 's/ghost/tkldev/' /etc/hosts

ghost install --verbose --url=http://localhost:2368 --db=mysql --dbhost=localhost --dbuser=ghost --dbpass=$DB_PASS --dbname=ghost --no-prompt --mail=sendmail --no-stack || true

sed -i 's/tkldev/ghost/' /etc/hosts

#ghost runs on 2368. Proxy to port 80 and port 443 (SSL/TLS)
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost

systemctl enable ghost_localhost.service

service mysql stop
